steps:
# This step will build and push new container image to "google container registry(GCR)"
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fnote-mfa', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fnote-mfa']

# This step will deploy the new container image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy', 'fnote-mfa-service', '--image=gcr.io/$PROJECT_ID/fnote-mfa', '--region=us-west4', '--allow-unauthenticated']